server:
  port: 8080
jwt:
  secret: YmU2ZDc5MTE5ZDAxZGFmMGQyYzgzZmZlMmZkMWFiMjVmYzBjMzIzZDEzZGM5N2IxZGZlNjU0ODQ2MDQwNzI5ZjFhOGEyNGY4N2M5OTlhMjMxNDVlOTJkODBhMGVkNGM5NWE4NjAxZWI1Y2ZiNWVlN2JhNThkMGQxYjhmMzczYTA=

azure:
  url: https://login.microsoftonline.com/%s/v2.0
  tenet: bb466cbb-621c-493b-8374-6c8f26dc6a18


