server:
  port: 8081

azure:
  uri:
    issuer: https://login.microsoftonline.com/%s/v2.0
    jwk: https://login.microsoftonline.com/%S/discovery/v2.0/keys
  tenet: 79d9b46d-d3cf-4c83-afd1-79a0f23a7ad1
